version: "3"
services:
    config-service:
        build: ./config-service/.
        image: tthttl/config-service
        ports: 
            - "8888:8888"
        networks:
            - internal
    discovery-service:
        build: ./discovery-service/.
        image: tthttl/discovery-service
        ports:
            - "8761:8761"
        depends_on: 
            - config-service
        networks:
            - internal
    gateway-service:
        build: ./gateway-service/.
        image: tthttl/gateway-service
        ports:
            - "8080:8080"
        depends_on:
            - config-service
            - discovery-service
        networks:
            - internal
networks:
    internal: