version: "3.1"
services:
    config-service:
        #build: ./config-service/.
        image: tthttl/config-service
        ports:
            - "8888:8888"
        networks:
            - internal
    discovery-service:
        #build: ./discovery-service/.
        image: tthttl/discovery-service
        ports:
            - "8761:8761"
        depends_on:
            - config-service
        networks:
            - internal
    gateway-service:
        #build: ./gateway-service/.
        image: tthttl/gateway-service
        ports:
            - "8080:8080"
        depends_on:
            - config-service
            - discovery-service
        networks:
            - internal
    tracing-service:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
        networks:
            - internal
    customer-db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: petclinic
        networks:
            - internal
        volumes:
            - ./customer-service:/docker-entrypoint-initdb.d
            - customer-data:/var/lib/mysql
    customer-service:
        #build: ./customer-service/.
        image: tthttl/customer-service
        ports:
            - "8081:8081"
        depends_on:
            - config-service
            - discovery-service
            - customer-db
        networks:
            - internal
        environment:
            WAIT_HOSTS: customer-db:3306
            WAIT_BEFORE_HOSTS: 30
            WAIT_HOSTS_TIMEOUT: 1000
            WAIT_SLEEP_INTERVAL: 30
    vet-db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: vetdb
        networks:
            - internal
        volumes:
            - ./vet-service:/docker-entrypoint-initdb.d
            - vet-data:/var/lib/mysql
    vet-service:
        #build: ./vet-service/.
        image: tthttl/vet-service
        ports:
            - "8090:8090"
        depends_on:
            - config-service
            - discovery-service
            - vet-db
        networks:
            - internal
        environment:
            WAIT_HOSTS: vet-db:3306
            WAIT_BEFORE_HOSTS: 30
            WAIT_HOSTS_TIMEOUT: 1000
            WAIT_SLEEP_INTERVAL: 30

    visit-db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: visitdb
        networks:
            - internal
        volumes:
            - ./visit-service:/docker-entrypoint-initdb.d
            - visit-data:/var/lib/mysql
    visit-service:
        #build: ./visit-service/.
        image: tthttl/visit-service
        ports:
            - "9000:9000"
        depends_on:
            - config-service
            - discovery-service
            - visit-db
        networks:
            - internal
        environment:
            WAIT_HOSTS: visit-db:3306
            WAIT_BEFORE_HOSTS: 30
            WAIT_HOSTS_TIMEOUT: 1000
            WAIT_SLEEP_INTERVAL: 30
    client-service:
        #build: ./client/tthttl-petclinic-client/.
        image: tthttl/petclinic-client
        ports:
            - "4200:80"
        networks:
            - internal
volumes:
    customer-data:
    vet-data:
    visit-data:

networks:
    internal: